from binary_heap import BHeap
import datetime
import math
import environment as env
from agent import Agent
from cell import Cell
# import pdb

infinity = 1000000 

def heuristic(a,b):
	''' Define your heuristic here. You can choose the Manhattan Distance as a starting point'''

def get_neighbors(cell,grid):
	''' Use this to retrieve all unblocked neighbors '''
	
def in_closed_list(closed_list,cell):
	for item in closed_list:
		if cell.equals(item):
			return True

	return False


def init_grid(grid,goal):	
	''' Initialize the grid '''

def reconstruct_path(came_from,current,size):
	''' Use this to reconstruct the path generated by your search'''

def a_star(start,goal,grid):
	''' Implement A* here '''
	
def compute_path(agent,goal,Tie_val,counter,expanded_states):
	''' Compute the path from the current state to the goal '''	


